source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# checkov:skip=CVE-2022-23517: Test CVE 1
# checkov:skip=rails-html-sanitizer[BC_LIC_1]: ADD License 1

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.1'
